# Generated by Django 4.1.7 on 2023-03-30 22:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_account_token'),
    ]

    operations = [
        migrations.CreateModel(
            name='Image',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('img', models.ImageField(upload_to='media/')),
                ('purpose', models.CharField(choices=[('CARD_PERSONAL_PIC', 'Персональное фото картчоки'), ('CARD_LOGO_PIC', 'Лого компании'), ('PORTFOLIO_PIC', 'Портфолио'), ('OTHER', 'Другое')], max_length=20)),
                ('date_create', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('date_update', models.DateTimeField(auto_now_add=True, verbose_name='Дата обновления')),
            ],
            options={
                'verbose_name': 'Изображения',
                'verbose_name_plural': 'Изображение',
            },
        ),
        migrations.RemoveField(
            model_name='card',
            name='logo_pic',
        ),
        migrations.RemoveField(
            model_name='card',
            name='personal_pic',
        ),
        migrations.RemoveField(
            model_name='portfolio',
            name='pic',
        ),
        migrations.AddField(
            model_name='card',
            name='id_img',
            field=models.ManyToManyField(to='api.image'),
        ),
        migrations.AddField(
            model_name='portfolio',
            name='id_img',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='api.image'),
        ),
    ]
