# Generated by Django 4.1.7 on 2023-03-30 22:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_image_remove_card_logo_pic_remove_card_personal_pic_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='card',
            name='id_img',
            field=models.ManyToManyField(blank=True, to='api.image'),
        ),
    ]
