# Generated by Django 4.1.7 on 2023-03-30 22:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_alter_card_id_img'),
    ]

    operations = [
        migrations.AlterField(
            model_name='companyinfo',
            name='id_card',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='api.card'),
        ),
    ]
