# Generated by Django 4.1.7 on 2023-03-30 22:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_alter_companyinfo_id_card'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='companyinfo',
            name='id_card',
        ),
        migrations.AddField(
            model_name='card',
            name='id_company_info',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='api.companyinfo'),
        ),
    ]
