# Generated by Django 4.1.7 on 2023-03-31 00:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_remove_companyinfo_id_card_card_id_company_info'),
    ]

    operations = [
        migrations.RenameField(
            model_name='portfolio',
            old_name='name',
            new_name='email',
        ),
    ]
