# Generated by Django 4.1.7 on 2023-04-02 00:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_rename_name_portfolio_email'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='card',
            name='id_img',
        ),
        migrations.AddField(
            model_name='card',
            name='logo_img',
            field=models.ImageField(default=1, upload_to='media/'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='card',
            name='personal_img',
            field=models.ImageField(default=1, upload_to='media/'),
            preserve_default=False,
        ),
    ]
