# Generated by Django 4.1.7 on 2023-04-03 21:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_remove_card_id_img_card_logo_img_card_personal_img'),
    ]

    operations = [
        migrations.AddField(
            model_name='companyinfo',
            name='logo_img',
            field=models.ImageField(blank=True, null=True, upload_to='media/'),
        ),
        migrations.AlterField(
            model_name='card',
            name='logo_img',
            field=models.ImageField(blank=True, null=True, upload_to='media/'),
        ),
        migrations.AlterField(
            model_name='card',
            name='personal_img',
            field=models.ImageField(blank=True, null=True, upload_to='media/'),
        ),
    ]
