# Generated by Django 4.1.7 on 2023-04-04 22:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0010_remove_social_odnoclassniki_social_odnoklassniki'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='social',
            name='tg',
        ),
        migrations.AddField(
            model_name='social',
            name='telegram',
            field=models.CharField(blank=True, max_length=250, null=True, verbose_name='telegram'),
        ),
    ]
