# Generated by Django 4.1.7 on 2023-04-06 00:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0011_remove_social_tg_social_telegram'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='portfolio',
            name='email',
        ),
        migrations.AddField(
            model_name='portfolio',
            name='name',
            field=models.CharField(blank=True, max_length=250, verbose_name='Название'),
        ),
    ]
