# Generated by Django 4.1.7 on 2023-04-06 00:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0012_remove_portfolio_email_portfolio_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='portfolio',
            name='id_img',
            field=models.ImageField(blank=True, null=True, upload_to='media/'),
        ),
    ]
