# Generated by Django 4.1.7 on 2023-04-07 03:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0014_rename_id_img_portfolio_img'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='card',
            name='qr',
        ),
        migrations.AddField(
            model_name='card',
            name='link',
            field=models.CharField(blank=True, max_length=250, verbose_name='link'),
        ),
    ]
