# Generated by Django 4.1.7 on 2023-04-09 22:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0015_remove_card_qr_card_link'),
    ]

    operations = [
        migrations.AddField(
            model_name='appearance',
            name='style',
            field=models.JSONField(blank=True, null=True, verbose_name='Стиль'),
        ),
    ]
