# Generated by Django 4.1.7 on 2023-04-28 04:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0016_appearance_style'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='social',
            name='beehance',
        ),
        migrations.AddField(
            model_name='social',
            name='behance',
            field=models.CharField(blank=True, max_length=250, null=True, verbose_name='behance'),
        ),
    ]
