# Generated by Django 4.1.7 on 2023-04-28 04:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0017_remove_social_beehance_social_behance'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='social',
            name='gmail',
        ),
        migrations.AddField(
            model_name='social',
            name='google',
            field=models.CharField(blank=True, max_length=250, null=True, verbose_name='google'),
        ),
    ]
