# Generated by Django 4.1.7 on 2023-05-03 17:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0019_subscription_account_id_subscription'),
    ]

    operations = [
        migrations.AddField(
            model_name='subscription',
            name='data',
            field=models.JSONField(default=dict),
        ),
    ]
