# Generated by Django 4.1.7 on 2023-05-03 18:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0020_subscription_data'),
    ]

    operations = [
        migrations.AlterField(
            model_name='card',
            name='dob',
            field=models.DateTimeField(verbose_name='Дата рождения'),
        ),
    ]
