# Generated by Django 4.2.1 on 2023-05-27 13:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0021_alter_card_dob'),
    ]

    operations = [
        migrations.AlterField(
            model_name='card',
            name='dob',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Дата рождения'),
        ),
    ]
