# Generated by Django 4.2.1 on 2023-06-26 15:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0023_alter_card_dob'),
    ]

    operations = [
        migrations.AlterField(
            model_name='portfolio',
            name='date',
            field=models.CharField(max_length=250, verbose_name='Подзаголовок'),
        ),
    ]
