# Generated by Django 4.1.7 on 2023-06-28 15:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0024_alter_portfolio_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='card',
            name='subcard',
            field=models.CharField(blank=True, max_length=250, null=True, verbose_name='Подкарта'),
        ),
    ]
