# Generated by Django 4.1.7 on 2023-06-28 15:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0025_card_subcard'),
    ]

    operations = [
        migrations.AlterField(
            model_name='card',
            name='subcard',
            field=models.CharField(blank=True, default='Портфолио', max_length=250, null=True, verbose_name='Подкарта'),
        ),
    ]
