# Generated by Django 4.1.7 on 2023-08-14 15:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0027_usersubsctibe'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='UserSubsctibe',
            new_name='UserSubscribe',
        ),
        migrations.RemoveField(
            model_name='card',
            name='dob',
        ),
        migrations.RemoveField(
            model_name='card',
            name='home_phone',
        ),
    ]
