# Generated by Django 4.2.1 on 2023-09-10 14:29

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0031_usersubscribe_payment_id_usersubscribe_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='usersubscribe',
            name='expire_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now, verbose_name='Истекает в'),
            preserve_default=False,
        ),
    ]
